import type { QueryBinary } from "@vlocode/salesforce";

interface ExpandFileDefinition {
    /**
     * When set it define the file name to which the export is written. For fields it would mean 
     * an new file is created to write the values in this field to. Only set if the intenion is to 
     * write the field value to a separate file instead of including it in the main datapack json file.
     *
     * When this is a string the string is parsed as format and values between brackets are replace by field values from the object to export, i.e `{Name}`.
     * When this is defined as an array each value in the array is evaluated as a field value expression and constants need to be prixed with a `_`:
     * ```yaml
     * name:
     * - Name
     * - _constantValue
     * # OR
     * name: "{Name}_constantValue"
     * ```
     * 
     * If no extension is provided the extension is inferred from the field type:
     * - json: .json
     * - binary: .bin
     */
    fileName?: string | string[];
}

/**
 * Definition of an object to export as part of a datapack, 
 * including filter conditions and related objects to include in the export.
 */
export type DatapackExportRelatedObject = ExportFieldDefinition & (ObjectFilter | ObjectRelationship) | string;

export interface DatapackExportDefinition extends ObjectFilter {
    /**
     * Name format of the datapack, used to create the folder name of the datapack, 
     * when a filename is not set this is also used as the file name.
     * 
     * When this is a string the string is parsed as format and values between brackets are replace by field values from the object to export, i.e `{Name}`.
     * When this is defined as an array each value in the array is evaluated as a field value expression and constants need to be prixed with a `_`:
     * ```yaml
     * name:
     * - Name
     * - _constantValue
     * # OR
     * name: "{Name}_constantValue"
     * ```
     */
    name: string | string[];
    /**
     * List of fields which uniquely identify the object and are used
     * for matching the object when importing and for generating the
     * external lookup reference.
     */
    matchingKeyFields?: string[];
    /**
     * When true the matching key is auto-generated random number instead of a value based on the object data.
     * autogenerated matching keys only work for none-lookup fields.
     */
    autoGeneratedMatchingKey?: boolean;
    /**
     * List of fields to exclude from the export.
     */
    ignoreFields?: string[];
    /**
     * List of objects that are related to this object
     * and who's data should be included in the export.
     * The key is the name under which related records are exported.
     */
    relatedObjects?: Record<string, DatapackExportRelatedObject>;
    /**
     * Optional object with specific export settings for fields in the object.
     */
    fields?: Record<string, ExportFieldDefinition>;
}

export interface ExportFieldDefinition extends ExpandFileDefinition {
    /**
     * Processor function snippet to use for processing the field data before exporting.
     */
    processor?: string;
    /**
     * When true expands an array value in the datapack to individual files.
     */
    expandArray?: boolean;
    /**
     * When this field is alookup field and this flag is set to true, 
     * the related record is exported as an embedded object in the same datapack instead of a separate datapack.
     */
    embeddedLookup?: boolean
    /**
     * When the field is a lookup and embeddedLookup is true, this array defines a list of fields to 
     * exclude from the export of the related record.
     * 
     * This can be used to prevent circular references when exporting related records as embedded objects. 
     * For example when exporting an Account with related Contacts as embedded objects, 
     * excluding the AccountId field from the Contact export will prevent circular reference 
     * between the Account and Contact datapacks.
     */
    ignoreFields?: string[];
    /**
     * List of fields by which to sort the exported data when exporting	as a related object.
     */
    sortFields?: string[];
}

export type LookupFilerPrimitive = string | number | boolean | null;
export type LookupFilerValue = { op: string, value: LookupFilerPrimitive };
type LookupFilterObject = { [key: string]: LookupFilerValue | LookupFilerPrimitive };
export type LookupFilter = string | LookupFilterObject | LookupFilterObject[];

export interface ObjectFilter {
    /**
     * Type of SObject to which this filter applies
     */
    objectType: string;
    /**
     * Where condition to filter the object data to export by.
     * Can be a string or an object. When an object, the key is the
     * field name and the value is the value to filter by. Accesing fields from the parent
     * datapack using bracket syntax `{}` is supported:
     * ```
     * filter:
     *  AccountId: $parent.Id
     *  IsActive: true
     * ```
     *
     * When defined as a string, the string is used as the where condition and
     * interpolated this allows for more complex where conditions:
     * ```yaml
     * filter: "AccountId = '{parent.Id}' AND IsActive = 'true'"
     * ```
     */
    filter?: LookupFilter;
    /**
     * Optional maximum number of records to return when querying this object.
     */
    limit?: number;
}

export interface ObjectRelationship {
    /**
     * Name of the relationship field on the parent object
     */
    relationshipName: string;
    /**
     * Optional filter to apply to the related object data to export.
     */
    filter?: LookupFilter;
}
