packages:
  - 'packages/*'
  - '!**/test/**'

publicHoistPattern:
  - 'ts-node'
  - 'eslint'
  - 'tslib'
  - 'eslint-config-*'
  - 'eslint-plugin-*'
  - 'prettier'
  - 'prettier-plugin-*'
  - '@rollup/*'
  - 'rollup'

resolutionMode: highest

dedupeDirectDeps: true

preferWorkspacePackages: true
