# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2

commands: 
  checkout_install:
    steps:
      - checkout
      - restore_cache:
          keys: 
          - pnpm-store-{{ checksum "pnpm-lock.yaml" }}
      - run: corepack enable && corepack prepare $(node -p "require('./package.json').packageManager") --activate
      - run: pnpm config set store-dir ~/.pnpm-store
      - run: pnpm install --frozen-lockfile
      - save_cache:
          key: pnpm-store-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store
  test:
    steps:
      - run: pnpm jest --ci --verbose -i
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage
  codequality:
    steps:
      - run: pnpm lint -o eslint-report.json --format json || true
      - sonarcloud/scan
  build:
    steps:
      - run: pnpm build

jobs:
  build-and-test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout_install
      - build
      - test
      - codequality
  package:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout_install
      - run: pnpm pack-extension
      - run: echo $(node -p "require('./lerna.json').version") > .version
      - persist_to_workspace:
          root: .
          paths: [ ".version", "*.vsix" ]
  publish-vsc-extension:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout_install
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish extension on VSCode Marketplace"
          command: |
            VERSION=$(cat ./artifacts/.version)
            pnpx vsce publish -p "$VSCE_TOKEN" --packagePath "./artifacts/vlocode-${VERSION}.vsix"
  publish-npm-packages:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout_install
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: pnpm lerna publish from-package --force-publish --no-push --yes
  github-release:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat ./artifacts/.version)
            ghr -t ${GITHUB_TOKEN} -n "Version ${VERSION}" -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete v${VERSION} ./artifacts/vlocode-${VERSION}.vsix

workflows:
  validate:
    jobs:
      - build-and-test:
          context: sonarcloud
  release:
    jobs:
      - package:
          context: vsce
          filters: &filters-publish
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - github-release:
          context: github
          filters: *filters-publish
          requires:
            - package
      - publish-approval:
          type: approval
          filters: *filters-publish
          requires:
            - package
            - github-release
      - publish-vsc-extension:
          context: vsce
          filters: *filters-publish
          requires:
            - publish-approval
      - publish-npm-packages:
          context: npm
          filters: *filters-publish
          requires:
            - publish-approval
