import 'jest';
import * as path from 'path';

import { DatapackExporter } from '../export/datapackExporter';
import { DatapackExpander } from '../export/datapackExpander';

describe('DatapackExporter', () => {

    function createLogger() {
        const logger = {
            debug: jest.fn(),
            error: jest.fn(),
            info: jest.fn(),
            verbose: jest.fn(),
            warn: jest.fn(),
            distinct: jest.fn()
        };
        logger.distinct.mockReturnValue(logger);
        return logger;
    }

    function findDescribeField(describe: any, fieldName: string) {
        return describe?.fields?.find((field: any) => field.name === fieldName) ?? {
            name: fieldName,
            referenceTo: []
        };
    }

    function createExporter(options?: {
        matchingKeyFields?: string[];
        matchingKeyFieldsByType?: Record<string, string[]>;
        describe?: any;
        describes?: Record<string, any>;
        records?: Array<Record<string, any>>;
        autoGeneratedObjects?: string[];
        embeddedObjects?: (item: any) => any[];
    }) {
        const records = new Map((options?.records ?? []).map(record => [record.Id, { id: record.Id, ...record }]));
        const autoGeneratedObjects = new Set(options?.autoGeneratedObjects ?? []);
        const describeFor = (type?: string) => type ? options?.describes?.[type] ?? options?.describe : options?.describe;
        const definitions = {
            getEmbeddedObjects: jest.fn((item: any) => options?.embeddedObjects?.(item) ?? []),
            getDatapackTypes: jest.fn(() => []),
            getMatchingKeyFields: jest.fn((item: any) =>
                options?.matchingKeyFieldsByType?.[item.objectType] ?? options?.matchingKeyFields ?? (options?.records ? ['Name'] : [])),
            getFieldsWith: jest.fn(() => []),
            isAutoGeneratedMatchingKey: jest.fn((item: any) => autoGeneratedObjects.has(item.objectType)),
            isEmbeddedObject: jest.fn(() => false),
            isFieldIgnored: jest.fn(() => false)
        };
        const salesforce = {
            data: {
                cache: {
                    configure: jest.fn()
                },
                lookup: jest.fn(async (objectType: string, filter: Record<string, any>) =>
                    [...records.values()].filter(record =>
                        record.__type === objectType &&
                        Object.entries(filter ?? {}).every(([field, value]) => record[field] === value)
                    )
                ),
                lookupById: jest.fn(async (ids: string | string[]) =>
                    Array.isArray(ids)
                        ? new Map(ids.map(id => [id, records.get(id)]))
                        : records.get(ids)),
                lookupMultiple: jest.fn(async (objectType: string, filters: Record<string, any>[]) =>
                    filters.map(filter => [...records.values()].filter(record =>
                        record.__type === objectType &&
                        Object.entries(filter ?? {}).every(([field, value]) => record[field] === value)
                    )))
            },
            schema: {
                describeSObjectById: jest.fn(async (id: string) => describeFor(records.get(id)?.__type)),
                describeSObjectField: jest.fn(async (type: string, fieldName: string) =>
                    findDescribeField(describeFor(type), fieldName))
            },
            replaceNamespace: jest.fn((value: string) => value)
        };
        const matchingKeys = {
            getMatchingKeyDefinition: jest.fn(async (type: string) => ({
                sobjectType: type,
                fields: [],
                returnField: 'Id'
            }))
        };

        const expander = {
            expandDatapack: jest.fn()
        };

        return {
            exporter: new DatapackExporter(
                definitions as any,
                expander as any,
                salesforce as any,
                salesforce.data as any,
                matchingKeys as any,
                createLogger() as any
            ) as any,
            expander,
            definitions,
            salesforce,
            matchingKeys
        };
    }

    it('keeps primitive filter values when evaluating embedded object filters', () => {
        const { exporter } = createExporter();
        const datapack = {
            id: '001000000000001AAA',
            objectType: 'Account',
            normalizedObjectType: 'Account',
            data: {
                Id: '001000000000001AAA'
            }
        };

        const filter = exporter.buildLookupFilter({
            ParentId: '{Account:Id}',
            IsActive: false,
            Count__c: 0,
            Optional__c: null
        }, datapack);

        expect(filter).toStrictEqual({
            ParentId: '001000000000001AAA',
            IsActive: false,
            Count__c: 0,
            Optional__c: null
        });
    });

    it('projects array values when evaluating exact filter placeholders', () => {
        const { exporter } = createExporter();
        const datapack = {
            id: '01t000000000001AAA',
            objectType: 'Product2',
            normalizedObjectType: 'Product2',
            data: {
                Id: '01t000000000001AAA',
                SBQQ__ProductFeature__c: [
                    { Id: 'a10000000000001AAA' },
                    { Id: 'a10000000000002AAA' }
                ]
            }
        };

        const filter = exporter.buildLookupFilter({
            SBQQ__Feature__c: '{Product2:SBQQ__ProductFeature__c:Id}'
        }, datapack);

        expect(filter).toStrictEqual({
            SBQQ__Feature__c: [
                'a10000000000001AAA',
                'a10000000000002AAA'
            ]
        });
    });

    it('drops OR filter branches with unresolved exact placeholders', () => {
        const { exporter } = createExporter();
        const datapack = {
            id: '01t000000000001AAA',
            objectType: 'Product2',
            normalizedObjectType: 'Product2',
            data: {
                Id: '01t000000000001AAA'
            }
        };

        const filter = exporter.buildLookupFilter([
            { SBQQ__Product__c: '{Product2:Id}' },
            { SBQQ__Feature__c: '{Product2:SBQQ__ProductFeature__c:Id}' }
        ], datapack);

        expect(filter).toStrictEqual([
            { SBQQ__Product__c: '01t000000000001AAA' }
        ]);
    });

    it('tries alternative datapack value paths in order', () => {
        const { exporter } = createExporter();
        const datapack = {
            id: '01t000000000001AAA',
            objectType: 'Product2',
            normalizedObjectType: 'Product2',
            data: {
                Id: '01t000000000001AAA'
            }
        };

        const filter = exporter.buildLookupFilter({
            Product__c: '{Product2:MissingId|Product2:Id}'
        }, datapack);

        expect(filter).toStrictEqual({
            Product__c: '01t000000000001AAA'
        });
    });

    it('stringifies projected arrays inside mixed filter strings', () => {
        const { exporter } = createExporter();
        const datapack = {
            id: '01t000000000001AAA',
            objectType: 'Product2',
            normalizedObjectType: 'Product2',
            data: {
                Id: '01t000000000001AAA',
                SBQQ__ProductFeature__c: [
                    { Id: 'a10000000000001AAA' },
                    { Id: 'a10000000000002AAA' }
                ]
            }
        };

        const filter = exporter.buildLookupFilter({
            Debug__c: 'features:{Product2:SBQQ__ProductFeature__c:Id}'
        }, datapack);

        expect(filter).toStrictEqual({
            Debug__c: 'features:a10000000000001AAA,a10000000000002AAA'
        });
    });

    it('resolves projected arrays inside string filters with mixed path separators', () => {
        const { exporter } = createExporter();
        const datapack = {
            id: '01t000000000001AAA',
            objectType: 'Product2',
            normalizedObjectType: 'Product2',
            data: {
                Id: '01t000000000001AAA',
                SBQQ__ProductFeature__c: [
                    { Id: 'a10000000000001AAA' },
                    { Id: 'a10000000000002AAA' }
                ]
            }
        };

        const filter = exporter.buildLookupFilter(
            "(SBQQ__Product__c = '{Product2:Id}') or (SBQQ__Feature__c IN ({Product2.SBQQ__ProductFeature__c:Id}))",
            datapack
        );

        expect(filter).toBe(
            "(SBQQ__Product__c = '01t000000000001AAA') or (SBQQ__Feature__c IN (a10000000000001AAA,a10000000000002AAA))"
        );
    });

    it('awaits lookup references included in matching key objects', async () => {
        const describe = {
            name: 'Child__c',
            fields: [
                { name: 'Parent__c', referenceTo: ['Parent__c'] },
                { name: 'Name', referenceTo: [] }
            ]
        };
        const { exporter } = createExporter({
            matchingKeyFields: ['Parent__c', 'Name'],
            describe
        });
        const parentLookup = {
            VlocityDataPackType: 'VlocityLookupMatchingKeyObject',
            VlocityRecordSObjectType: 'Parent__c',
            VlocityLookupRecordSourceKey: 'Parent__c/Parent'
        };
        exporter.buildLookup = jest.fn(() => parentLookup);

        const result = await exporter.buildMatchingKeyObject(
            { scope: undefined },
            'VlocityLookupMatchingKeyObject',
            {
                id: 'a01000000000001AAA',
                Id: 'a01000000000001AAA',
                Parent__c: 'a00000000000001AAA',
                Name: 'Child'
            }
        );

        expect(exporter.buildLookup).toHaveBeenCalledWith(
            { scope: undefined },
            'a00000000000001AAA',
            'VlocityLookupMatchingKeyObject',
            'Parent__c'
        );
        expect(result.Parent__c).toBe(parentLookup);
        expect(result.Parent__c).not.toHaveProperty('then');
    });

    it('uses DeveloperName before the name field for unscoped SObject matching keys', async () => {
        const describe = {
            name: 'CustomMetadata__mdt',
            fields: [
                { name: 'Id', referenceTo: [] },
                { name: 'Name', nameField: true, autoNumber: false, calculated: false, referenceTo: [] },
                { name: 'DeveloperName', referenceTo: [] }
            ]
        };
        const { exporter, matchingKeys } = createExporter({ describe });

        const result = await exporter.getMatchingKey(
            describe,
            {
                id: 'm00000000000001AAA',
                Id: 'm00000000000001AAA',
                Name: 'Display Name',
                DeveloperName: 'Stable_Developer_Name'
            }
        );

        expect(result).toBe('CustomMetadata__mdt/Stable_Developer_Name');
        expect(matchingKeys.getMatchingKeyDefinition).not.toHaveBeenCalled();
    });

    it('uses the name field for unscoped SObject matching keys without DeveloperName', async () => {
        const describe = {
            name: 'Account',
            fields: [
                { name: 'Id', referenceTo: [] },
                { name: 'Name', nameField: true, autoNumber: false, calculated: false, referenceTo: [] },
                { name: 'LegacyKey__c', referenceTo: [] }
            ]
        };
        const { exporter, matchingKeys } = createExporter({ describe });

        const result = await exporter.getMatchingKey(
            describe,
            {
                id: '001000000000001AAA',
                Id: '001000000000001AAA',
                Name: 'Acme',
                LegacyKey__c: null
            }
        );

        expect(result).toBe('Account/Acme');
        expect(matchingKeys.getMatchingKeyDefinition).not.toHaveBeenCalled();
    });

    it('blocks top-level datapacks that have no matching key', async () => {
        const describe = {
            name: 'Generated__c',
            fields: [
                { name: 'Id', referenceTo: [] },
                { name: 'Name', referenceTo: [] },
                { name: 'ExternalKey__c', referenceTo: [] }
            ],
            childRelationships: []
        };
        const createHarness = () => createExporter({
            matchingKeyFieldsByType: {
                // matching field is present but empty on the record -> would fall back to auto-generated
                Generated__c: ['ExternalKey__c']
            },
            describes: { Generated__c: describe },
            records: [{ Id: 'a00000000000001AAA', __type: 'Generated__c', Name: 'Generated', ExternalKey__c: null }]
        });

        // With failOnError the export rejects rather than emitting an auto-generated top-level key.
        await expect(createHarness().exporter.exportObject('a00000000000001AAA', { maxDepth: 0, failOnError: true }))
            .rejects.toThrow(/matching key/i);

        // Without failOnError the unexportable record is skipped, not given a generated key.
        const skipped = await createHarness().exporter.exportObject('a00000000000001AAA', { maxDepth: 0 });
        expect(skipped).toHaveLength(0);
    });

    it('suppresses nulls and strips source keys from unreferenced embedded records', async () => {
        const parentAD = 'a00000000000001AAA';
        const parentBD = 'a00000000000002AAA';
        const childAD = 'a01000000000001AAA';
        const childBD = 'a01000000000002AAA';
        const parentDescribe = {
            name: 'Parent__c',
            fields: [
                { name: 'Id', referenceTo: [] },
                { name: 'Name', referenceTo: [] },
                { name: 'Optional__c', referenceTo: [] },
                { name: 'Enabled__c', referenceTo: [] },
                { name: 'Count__c', referenceTo: [] },
                { name: 'Text__c', referenceTo: [] },
                { name: 'Json__c', referenceTo: [] }
            ],
            childRelationships: []
        };
        const childDescribe = {
            name: 'Child__c',
            fields: [
                { name: 'Id', referenceTo: [] },
                { name: 'Name', referenceTo: [] },
                { name: 'Parent__c', referenceTo: ['Parent__c'] },
                { name: 'Optional__c', referenceTo: [] }
            ],
            childRelationships: []
        };
        const { exporter } = createExporter({
            autoGeneratedObjects: ['Child__c'],
            describes: {
                Parent__c: parentDescribe,
                Child__c: childDescribe
            },
            records: [
                { Id: parentAD, __type: 'Parent__c', Name: 'Parent A', Optional__c: null, Enabled__c: false, Count__c: 0, Text__c: '', Json__c: '{"preserve":null}' },
                { Id: parentBD, __type: 'Parent__c', Name: 'Parent B', Optional__c: null, Enabled__c: false, Count__c: 0, Text__c: '', Json__c: '{"preserve":null}' },
                { Id: childAD, __type: 'Child__c', Name: 'Same Child', Parent__c: parentAD, Optional__c: null },
                { Id: childBD, __type: 'Child__c', Name: 'Same Child', Parent__c: parentBD, Optional__c: null }
            ],
            embeddedObjects: item => item.objectType === 'Parent__c'
                ? [{ name: 'Children__r', objectType: 'Child__c', filter: { Parent__c: '{Parent__c:Id}' } }]
                : []
        });

        const results = await exporter.exportObject([parentAD, parentBD], { maxDepth: 0, suppressNulls: true });
        const resultsByKey = new Map(results.map(result => [result.sourceKey, result]));
        const parentA = resultsByKey.get('Parent__c/Parent A')!.datapack;
        const childA = parentA.Children__r[0];
        const childB = resultsByKey.get('Parent__c/Parent B')!.datapack.Children__r[0];

        expect(parentA).not.toHaveProperty('Optional__c');
        expect(parentA.Enabled__c).toBe(false);
        expect(parentA.Count__c).toBe(0);
        expect(parentA.Text__c).toBe('');
        expect(parentA.Json__c).toStrictEqual({ preserve: null });
        expect(childA).not.toHaveProperty('Optional__c');
        expect(childA.Parent__c.VlocityMatchingRecordSourceKey).toBe('Parent__c/Parent A');
        expect(childB.Parent__c.VlocityMatchingRecordSourceKey).toBe('Parent__c/Parent B');
        // Auto-generated embedded records that are never referenced drop their source key; the
        // deploy side synthesizes one. Only referenced embedded records keep a (cheap) key.
        expect(childA).not.toHaveProperty('VlocityRecordSourceKey');
        expect(childB).not.toHaveProperty('VlocityRecordSourceKey');
    });

    it('batches array-clause embedded filters across parents into one query', async () => {
        const parentAD = 'a00000000000001AAA';
        const parentBD = 'a00000000000002AAA';
        const describes = {
            Parent__c: {
                name: 'Parent__c',
                fields: [{ name: 'Id', referenceTo: [] }, { name: 'Name', referenceTo: [] }],
                childRelationships: []
            },
            Child__c: {
                name: 'Child__c',
                fields: [
                    { name: 'Id', referenceTo: [] },
                    { name: 'Name', referenceTo: [] },
                    { name: 'Parent__c', referenceTo: ['Parent__c'] }
                ],
                childRelationships: []
            }
        };
        const { exporter, salesforce } = createExporter({
            matchingKeyFieldsByType: { Parent__c: ['Name'], Child__c: ['Name'] },
            describes,
            records: [
                { Id: parentAD, __type: 'Parent__c', Name: 'Parent A' },
                { Id: parentBD, __type: 'Parent__c', Name: 'Parent B' },
                { Id: 'a01000000000001AAA', __type: 'Child__c', Name: 'Child A', Parent__c: parentAD },
                { Id: 'a01000000000002AAA', __type: 'Child__c', Name: 'Child B', Parent__c: parentBD }
            ],
            // filter expressed as a single-element array (YAML list form) -> must still batch
            embeddedObjects: item => item.objectType === 'Parent__c'
                ? [{ name: 'Children__r', objectType: 'Child__c', filter: [{ Parent__c: '{Parent__c:Id}' }] }]
                : []
        });

        const results = await exporter.exportObject([parentAD, parentBD], { maxDepth: 0 });
        const byKey = new Map(results.map(result => [result.sourceKey, result.datapack]));

        // One batched query for both parents, not one per parent.
        expect(salesforce.data.lookupMultiple).toHaveBeenCalledTimes(1);
        expect(byKey.get('Parent__c/Parent A')!.Children__r[0].Name).toBe('Child A');
        expect(byKey.get('Parent__c/Parent B')!.Children__r[0].Name).toBe('Child B');
    });

    it('respects failOnError for embedded matching key collisions', async () => {
        const parentD = 'a00000000000001AAA';
        const describes = {
            Parent__c: {
                name: 'Parent__c',
                fields: [{ name: 'Id', referenceTo: [] }, { name: 'Name', referenceTo: [] }],
                childRelationships: []
            },
            Child__c: {
                name: 'Child__c',
                fields: [
                    { name: 'Id', referenceTo: [] },
                    { name: 'Name', referenceTo: [] },
                    { name: 'Parent__c', referenceTo: ['Parent__c'] }
                ],
                childRelationships: []
            }
        };
        // Two children share the same matching key (Name) -> the second is a collision.
        const makeExporter = () => createExporter({
            matchingKeyFieldsByType: { Parent__c: ['Name'], Child__c: ['Name'] },
            describes,
            records: [
                { Id: parentD, __type: 'Parent__c', Name: 'P' },
                { Id: 'a01000000000001AAA', __type: 'Child__c', Name: 'Dup', Parent__c: parentD },
                { Id: 'a01000000000002AAA', __type: 'Child__c', Name: 'Dup', Parent__c: parentD }
            ],
            embeddedObjects: item => item.objectType === 'Parent__c'
                ? [{ name: 'Children__r', objectType: 'Child__c', filter: { Parent__c: '{Parent__c:Id}' } }]
                : []
        });

        // failOnError: the collision aborts the whole export.
        await expect(makeExporter().exporter.exportObject(parentD, { maxDepth: 0, failOnError: true }))
            .rejects.toThrow(/not unique/i);

        // otherwise the colliding child is skipped and the rest still exports.
        const results = await makeExporter().exporter.exportObject(parentD, { maxDepth: 0 });
        expect(results).toHaveLength(1);
        expect(results[0].datapack.Children__r).toHaveLength(1);
    });

    it('counts embedded children in the reported progress total', async () => {
        const parentD = 'a00000000000001AAA';
        const { exporter } = createExporter({
            matchingKeyFieldsByType: { Parent__c: ['Name'], Child__c: ['Name'] },
            describes: {
                Parent__c: {
                    name: 'Parent__c',
                    fields: [{ name: 'Id', referenceTo: [] }, { name: 'Name', referenceTo: [] }],
                    childRelationships: []
                },
                Child__c: {
                    name: 'Child__c',
                    fields: [
                        { name: 'Id', referenceTo: [] },
                        { name: 'Name', referenceTo: [] },
                        { name: 'Parent__c', referenceTo: ['Parent__c'] }
                    ],
                    childRelationships: []
                }
            },
            records: [
                { Id: parentD, __type: 'Parent__c', Name: 'P' },
                { Id: 'a01000000000001AAA', __type: 'Child__c', Name: 'C1', Parent__c: parentD },
                { Id: 'a01000000000002AAA', __type: 'Child__c', Name: 'C2', Parent__c: parentD }
            ],
            embeddedObjects: item => item.objectType === 'Parent__c'
                ? [{ name: 'Children__r', objectType: 'Child__c', filter: { Parent__c: '{Parent__c:Id}' } }]
                : []
        });

        const updates: Array<{ progress: number; total: number }> = [];
        await exporter.exportObject(parentD, { maxDepth: 0, onProgress: (u: any) => updates.push({ progress: u.progress, total: u.total }) });

        // total starts at 1 root and grows to include the 2 embedded children once discovered.
        expect(updates[0].total).toBe(1);
        const last = updates[updates.length - 1];
        expect(last.total).toBe(3);
        expect(last.progress).toBe(3);
    });

    it('gives referenced embedded auto-generated records a cheap path source key', async () => {
        const parentD = 'a00000000000001AAA';
        const ruleD = 'a01000000000001AAA';
        const conditionD = 'a02000000000001AAA';
        const describes = {
            Parent__c: {
                name: 'Parent__c',
                fields: [{ name: 'Id', referenceTo: [] }, { name: 'Name', referenceTo: [] }],
                childRelationships: []
            },
            Rule__c: {
                name: 'Rule__c',
                fields: [
                    { name: 'Id', referenceTo: [] },
                    { name: 'Name', referenceTo: [] },
                    { name: 'Parent__c', referenceTo: ['Parent__c'] }
                ],
                childRelationships: []
            },
            Condition__c: {
                name: 'Condition__c',
                fields: [
                    { name: 'Id', referenceTo: [] },
                    { name: 'Name', referenceTo: [] },
                    { name: 'Parent__c', referenceTo: ['Parent__c'] },
                    { name: 'Rule__c', referenceTo: ['Rule__c'] }
                ],
                childRelationships: []
            }
        };
        const { exporter } = createExporter({
            autoGeneratedObjects: ['Rule__c', 'Condition__c'],
            matchingKeyFieldsByType: { Parent__c: ['Name'] },
            describes,
            records: [
                { Id: parentD, __type: 'Parent__c', Name: 'Parent A' },
                { Id: ruleD, __type: 'Rule__c', Name: 'R1', Parent__c: parentD },
                { Id: conditionD, __type: 'Condition__c', Name: 'C1', Parent__c: parentD, Rule__c: ruleD }
            ],
            embeddedObjects: item => item.objectType === 'Parent__c'
                ? [
                    { name: 'Rules__r', objectType: 'Rule__c', filter: { Parent__c: '{Parent__c:Id}' } },
                    { name: 'Conditions__r', objectType: 'Condition__c', filter: { Parent__c: '{Parent__c:Id}' } }
                ]
                : []
        });

        const results = await exporter.exportObject([parentD], { maxDepth: 0 });
        const parent = results[0].datapack;
        const rule = parent.Rules__r[0];
        const condition = parent.Conditions__r[0];

        // Rule is referenced by the condition -> gets a cheap, datapack-local path key.
        expect(rule.VlocityRecordSourceKey).toBe('Parent__c/Parent A/Rule__c/0');
        expect(condition.Rule__c.VlocityMatchingRecordSourceKey).toBe('Parent__c/Parent A/Rule__c/0');
        // Condition is referenced by nothing -> key stripped.
        expect(condition).not.toHaveProperty('VlocityRecordSourceKey');
    });

    it('defers lookup matching key object expansion until references are resolved', async () => {
        const relatedId = 'a01000000000001AAA';
        const relatedDescribe = {
            name: 'Related__c',
            fields: [
                { name: 'Id', referenceTo: [] },
                { name: 'Name', referenceTo: [] }
            ],
            childRelationships: []
        };
        const definitions = {
            getMatchingKeyFields: jest.fn(() => ['Name']),
            isAutoGeneratedMatchingKey: jest.fn(() => false)
        };
        const salesforce = {
            data: {
                lookupById: jest.fn(async (ids: string[]) => new Map(ids.map(id => [
                    id,
                    id === relatedId ? { Id: relatedId, id: relatedId, Name: 'Related' } : undefined
                ])))
            },
            schema: {
                describeSObjectById: jest.fn(async () => relatedDescribe),
                describeSObjectField: jest.fn(async (_type: string, fieldName: string) =>
                    findDescribeField(relatedDescribe, fieldName))
            }
        };
        const exporter = new DatapackExporter(
            definitions as any,
            { expandDatapack: jest.fn() } as any,
            salesforce as any,
            salesforce.data as any,
            { getMatchingKeyDefinition: jest.fn() } as any,
            createLogger() as any
        ) as any;
        const datapack = {
            id: 'a00000000000001AAA',
            objectType: 'Root__c',
            normalizedObjectType: 'Root__c',
            references: {},
            foreignKeys: {},
            sourceKeys: {},
            idToSourceKey: {},
            data: {}
        };
        exporter.datapacks.set(datapack.id, datapack);

        const reference = await exporter.buildLookup(datapack, relatedId, 'VlocityLookupMatchingKeyObject', 'Related__c');

        expect(reference).toMatchObject({
            VlocityDataPackType: 'VlocityLookupMatchingKeyObject',
            VlocityRecordSObjectType: 'Related__c',
            VlocityLookupRecordSourceKey: relatedId
        });
        expect(salesforce.data.lookupById).not.toHaveBeenCalled();

        await exporter.resolveDeferredLookups();

        expect(salesforce.data.lookupById).toHaveBeenCalledWith([relatedId]);
        expect(reference).toMatchObject({
            Name: 'Related',
            VlocityDataPackType: 'VlocityLookupMatchingKeyObject',
            VlocityRecordSObjectType: 'Related__c',
            VlocityLookupRecordSourceKey: 'Related__c/Related'
        });
        expect(datapack.foreignKeys).toStrictEqual({
            'Related__c/Related': relatedId
        });
    });

    it('preserves already resolved foreign key source keys when deferred references are normalized', () => {
        const { exporter } = createExporter();
        const unresolvedId = 'a01000000000001AAA';
        const alreadyResolvedId = 'a02000000000001AAA';
        const datapack = {
            id: 'a00000000000001AAA',
            sourceKeys: {},
            idToSourceKey: {},
            foreignKeys: {
                [unresolvedId]: unresolvedId,
                'Already__c/Resolved': alreadyResolvedId
            }
        };
        (exporter as any).datapacks.set(datapack.id, datapack);
        (exporter as any).sourceKeyById.set(unresolvedId, 'Related__c/Related');

        (exporter as any).normalizeForeignKeys();

        expect(datapack.foreignKeys).toStrictEqual({
            'Related__c/Related': unresolvedId,
            'Already__c/Resolved': alreadyResolvedId
        });
    });

    it('passes export scope to the expander', async () => {
        const { exporter, expander } = createExporter();
        const datapack = {
            VlocityRecordSObjectType: 'OmniProcess',
            VlocityRecordSourceKey: 'OmniProcess/Test'
        };
        exporter.exportObject = jest.fn(async () => [{
            datapack,
            objectType: 'OmniProcess',
            parentKeys: [],
            sourceKey: 'OmniProcess/Test'
        }]);

        await exporter.exportObjectAndExpand('0jN000000000001AAA', { scope: 'OmniScript' });

        expect(expander.expandDatapack).toHaveBeenCalledWith(datapack, { scope: 'OmniScript' });
    });

    it('passes per-request export scope to the expander', async () => {
        const { exporter, expander } = createExporter();
        const datapack = {
            VlocityRecordSObjectType: 'OmniProcess',
            VlocityRecordSourceKey: 'OmniProcess/Test'
        };
        exporter.exportObject = jest.fn(async () => [{
            datapack,
            objectType: 'OmniProcess',
            parentKeys: [],
            relatedDatapacks: [],
            sourceKey: 'OmniProcess/Test',
            scope: 'std'
        }]);

        await exporter.exportObjectAndExpand([{ id: '0jN000000000001AAA', scope: 'std' }]);

        expect(expander.expandDatapack).toHaveBeenCalledWith(datapack, { scope: 'std' });
    });

    it('exports lookup-related objects within the selected dependency depth', async () => {
        const rootId = 'a00000000000001AAA';
        const relatedId = 'a01000000000001AAA';
        const rootDescribe = {
            name: 'Root__c',
            fields: [
                { name: 'Id', referenceTo: [] },
                { name: 'Name', referenceTo: [] },
                { name: 'Lookup__c', referenceTo: ['Related__c'] }
            ],
            childRelationships: []
        };
        const relatedDescribe = {
            name: 'Related__c',
            fields: [
                { name: 'Id', referenceTo: [] },
                { name: 'Name', referenceTo: [] }
            ],
            childRelationships: []
        };
        const definitions = {
            getEmbeddedObjects: jest.fn(() => []),
            getDatapackTypes: jest.fn(() => []),
            getMatchingKeyFields: jest.fn(() => ['Name']),
            getFieldsWith: jest.fn(() => []),
            isAutoGeneratedMatchingKey: jest.fn(() => false),
            isEmbeddedObject: jest.fn(() => false),
            isFieldIgnored: jest.fn(() => false)
        };
        const recordsById = new Map([
            [rootId, { Id: rootId, id: rootId, Name: 'Root', Lookup__c: relatedId }],
            [relatedId, { Id: relatedId, id: relatedId, Name: 'Related' }]
        ]);
        const salesforce = {
            data: {
                cache: {
                    configure: jest.fn()
                },
                lookupById: jest.fn(async (ids: string | string[]) => Array.isArray(ids)
                    ? new Map(ids.map(id => [id, recordsById.get(id)]))
                    : recordsById.get(ids))
            },
            schema: {
                describeSObjectById: jest.fn(async (id: string) => id === rootId ? rootDescribe : relatedDescribe),
                describeSObjectField: jest.fn(async (type: string, fieldName: string) =>
                    findDescribeField(type === rootDescribe.name ? rootDescribe : relatedDescribe, fieldName))
            },
            replaceNamespace: jest.fn((value: string) => value)
        };
        const matchingKeys = {
            getMatchingKeyDefinition: jest.fn(async (type: string) => ({
                sobjectType: type,
                fields: [],
                returnField: 'Id'
            }))
        };
        const expandedResults: any[] = [];
        const expander = {
            expandDatapack: jest.fn((datapack) => {
                const result = {
                    baseName: datapack.Name,
                    folder: datapack.Name,
                    objectType: datapack.VlocityRecordSObjectType,
                    sourceKey: datapack.VlocityRecordSourceKey,
                    parentKeys: [],
                    files: {},
                    writeToFilesystem: jest.fn(async () => [])
                };
                expandedResults.push(result);
                return result;
            })
        };
        const exporter = new DatapackExporter(
            definitions as any,
            expander as any,
            salesforce as any,
            salesforce.data as any,
            matchingKeys as any,
            createLogger() as any
        ) as any;
        exporter.data = salesforce.data;
        exporter.maxExportDepth = 1;

        const result = await exporter.exportObjectAndExpand(rootId);

        expect(expander.expandDatapack).toHaveBeenCalledTimes(2);
        const rootDatapack = expander.expandDatapack.mock.calls[0][0];
        const relatedDatapack = expander.expandDatapack.mock.calls[1][0];
        expect(rootDatapack.Lookup__c).toMatchObject({
            VlocityDataPackType: 'VlocityLookupMatchingKeyObject',
            VlocityLookupRecordSourceKey: 'Related__c/Related'
        });
        expect(relatedDatapack).toMatchObject({
            VlocityDataPackType: 'SObject',
            VlocityRecordSObjectType: 'Related__c',
            VlocityRecordSourceKey: 'Related__c/Related'
        });
        // Related is exported as its own top-level datapack (separate expand call above), referenced by
        // the root via lookup rather than embedded inside it.
        expect(rootDatapack).not.toHaveProperty('Related__c');
        expect(result).toHaveLength(2);
        await result[0].writeToFilesystem('/tmp/out');
        await result[1].writeToFilesystem('/tmp/out');
        expect(expandedResults[0].writeToFilesystem).toHaveBeenCalledWith('/tmp/out');
        expect(expandedResults[1].writeToFilesystem).toHaveBeenCalledWith('/tmp/out');
        expect(salesforce.data.lookupById).toHaveBeenCalledWith([rootId]);
        expect(salesforce.data.lookupById).toHaveBeenCalledWith([relatedId]);
    });

    it('builds embedded objects from the records returned by the embedded lookup even at root-only depth', async () => {
        const childId = 'a01000000000001AAA';
        const parentDatapack = {
            id: 'a00000000000001AAA',
            objectType: 'Parent__c',
            normalizedObjectType: 'Parent__c',
            schema: {
                name: 'Parent__c',
                fields: [],
                childRelationships: []
            },
            data: {
                Id: 'a00000000000001AAA',
                VlocityRecordSourceKey: 'Parent__c/Parent'
            },
            children: {},
            references: {},
            foreignKeys: {},
            sourceKeys: {
                'Parent__c/Parent': 'a00000000000001AAA'
            },
            idToSourceKey: {
                'a00000000000001AAA': 'Parent__c/Parent'
            },
            dependencyDepth: 0
        };
        const childDescribe = {
            name: 'Child__c',
            fields: [
                { name: 'Id', referenceTo: [] },
                { name: 'Name', referenceTo: [] }
            ],
            childRelationships: []
        };
        const definitions = {
            getEmbeddedObjects: jest.fn(item => item.objectType === 'Parent__c'
                ? [{
                    name: 'Child__c',
                    objectType: 'Child__c',
                    filter: { Parent__c: '{Parent__c:Id}' }
                }]
                : []),
            getDatapackTypes: jest.fn(() => []),
            getMatchingKeyFields: jest.fn(() => ['Name']),
            getFieldsWith: jest.fn(() => []),
            isAutoGeneratedMatchingKey: jest.fn(() => false),
            isEmbeddedObject: jest.fn(() => false),
            isFieldIgnored: jest.fn(() => false)
        };
        const childRecord = {
            Id: childId,
            id: childId,
            Name: 'Child'
        };
        const salesforce = {
            data: {
                cache: {
                    configure: jest.fn()
                },
                lookup: jest.fn(async () => [childRecord]),
                lookupMultiple: jest.fn(async () => [[childRecord]]),
                lookupById: jest.fn(async (ids: string | string[]) => Array.isArray(ids)
                    ? new Map(ids.map(id => [id, id === childId ? childRecord : undefined]))
                    : ids === childId ? childRecord : undefined)
            },
            schema: {
                describeSObjectById: jest.fn(async () => childDescribe),
                describeSObjectField: jest.fn(async (_type: string, fieldName: string) =>
                    findDescribeField(childDescribe, fieldName))
            },
            replaceNamespace: jest.fn((value: string) => value)
        };
        const matchingKeys = {
            getMatchingKeyDefinition: jest.fn(async (type: string) => ({
                sobjectType: type,
                fields: [],
                returnField: 'Id'
            }))
        };

        const exporter = new DatapackExporter(
            definitions as any,
            { expandDatapack: jest.fn() } as any,
            salesforce as any,
            salesforce.data as any,
            matchingKeys as any,
            createLogger() as any
        ) as any;
        exporter.data = salesforce.data;
        exporter.maxExportDepth = 0;

        await exporter.exportEmbeddedObjects(parentDatapack, { currentDepth: 0, maxDepth: 0 });
        await exporter.resolveEmbeddedObjects();

        expect(salesforce.data.lookupMultiple).toHaveBeenCalledTimes(1);
        expect((parentDatapack.data as any).Child__c).toHaveLength(1);
        expect((parentDatapack.data as any).Child__c[0].VlocityDataPackType).toBe('SObject');
        expect((parentDatapack.data as any).Child__c[0].Name).toBe('Child');
    });
});

describe('DatapackExpander', () => {

    function createLogger() {
        return {
            debug: jest.fn(),
            error: jest.fn(),
            info: jest.fn(),
            verbose: jest.fn(),
            warn: jest.fn()
        };
    }

    it('expands configured array fields into separate files', () => {
        const definitions = {
            getFileName: jest.fn((_item, field) => field === undefined ? ['Name'] : field === 'Children' ? ['_Child', 'Name'] : undefined),
            getName: jest.fn(() => ['Name']),
            getFieldConfig: jest.fn((_item, field, configKey) => field === 'Children' && configKey === 'expandArray')
        };
        const expander = new DatapackExpander(definitions as any, createLogger() as any);

        const result = expander.expandDatapack({
            VlocityDataPackType: 'SObject',
            VlocityRecordSObjectType: 'Parent__c',
            VlocityRecordSourceKey: 'Parent__c/Parent',
            Name: 'Parent',
            Children: [
                { Name: 'First' },
                { Name: 'Second' }
            ]
        });

        expect(Object.keys(result.files).sort()).toStrictEqual([
            'Parent_Child_First.json',
            'Parent_Child_Second.json',
            'Parent_DataPack.json'
        ]);
        expect(JSON.parse(result.files['Parent_DataPack.json'].toString()).Children).toStrictEqual([
            'Parent_Child_First.json',
            'Parent_Child_Second.json'
        ]);
    });

    it('keeps configured null fields inline instead of expanding them into files', () => {
        const definitions = {
            getFileName: jest.fn((_item, field) => field === undefined ? ['Name'] : field === 'PropertySet' ? ['_PropertySet'] : undefined),
            getName: jest.fn(() => ['Name']),
            getFieldConfig: jest.fn()
        };
        const expander = new DatapackExpander(definitions as any, createLogger() as any);

        const result = expander.expandDatapack({
            VlocityDataPackType: 'SObject',
            VlocityRecordSObjectType: 'Parent__c',
            VlocityRecordSourceKey: 'Parent__c/Parent',
            Name: 'Parent',
            PropertySet: null
        });

        expect(Object.keys(result.files).sort()).toStrictEqual([
            'Parent_DataPack.json'
        ]);
        expect(JSON.parse(result.files['Parent_DataPack.json'].toString()).PropertySet).toBeNull();
    });

    it('uses the source key name for unconfigured generic SObject folders', () => {
        const definitions = {
            getFileName: jest.fn(),
            getName: jest.fn(),
            getFieldConfig: jest.fn()
        };
        const expander = new DatapackExpander(definitions as any, createLogger() as any);

        const result = expander.expandDatapack({
            VlocityDataPackType: 'SObject',
            VlocityRecordSObjectType: 'Account',
            VlocityRecordSourceKey: 'Account/Acme',
            Name: 'Acme'
        });

        expect(result.folder).toBe('Account/Acme');
        expect(Object.keys(result.files)).toStrictEqual([
            'Acme_DataPack.json'
        ]);
    });

    it('sanitizes separators in configured folder and file names', () => {
        const definitions = {
            getFileName: jest.fn((_item, field) => field === undefined ? ['FolderName'] : undefined),
            getName: jest.fn(() => ['FolderName']),
            getFieldConfig: jest.fn()
        };
        const expander = new DatapackExpander(definitions as any, createLogger() as any);

        const result = expander.expandDatapack({
            VlocityDataPackType: 'SObject',
            VlocityRecordSObjectType: 'Product_Specification__c',
            VlocityRecordSourceKey: 'Product_Specification__c/auto-generated/71044b66',
            FolderName: 'auto-generated/71044b66'
        }, { datapackType: 'SObject' });

        expect(result.folder).toBe('SObject_Product_Specification_c/auto-generated_71044b66');
        expect(Object.keys(result.files)).toStrictEqual([
            'auto-generated_71044b66_DataPack.json'
        ]);
    });

    it('falls back to the source key name when a configured folder field is empty', () => {
        const definitions = {
            getFileName: jest.fn((_item, field) => field === undefined ? ['FolderName'] : undefined),
            getName: jest.fn(() => ['FolderName']),
            getFieldConfig: jest.fn()
        };
        const expander = new DatapackExpander(definitions as any, createLogger() as any);

        const result = expander.expandDatapack({
            VlocityDataPackType: 'SObject',
            VlocityRecordSObjectType: 'Account',
            VlocityRecordSourceKey: 'Account/Acme',
            FolderName: null
        });

        expect(result.folder).toBe('Account/Acme');
        expect(Object.keys(result.files)).toStrictEqual([
            'Acme_DataPack.json'
        ]);
    });

    it('keeps configured field file extensions and writes non-json strings raw', () => {
        const definitions = {
            getFileName: jest.fn((_item, field) => field === undefined ? ['Name'] : field === 'Code__c' ? ['_Script.js'] : undefined),
            getName: jest.fn(() => ['Name']),
            getFieldConfig: jest.fn()
        };
        const expander = new DatapackExpander(definitions as any, createLogger() as any);

        const result = expander.expandDatapack({
            VlocityDataPackType: 'SObject',
            VlocityRecordSObjectType: 'CustomScript__c',
            VlocityRecordSourceKey: 'CustomScript__c/Test',
            Name: 'Test.v1',
            Code__c: 'export default {};\n'
        });

        expect(Object.keys(result.files).sort()).toStrictEqual([
            'Test-v1_DataPack.json',
            'Test-v1_Script.js'
        ]);
        expect(result.files['Test-v1_Script.js'].toString()).toBe('export default {};\n');
    });

    it('writes expanded files to the filesystem', async () => {
        const definitions = {
            getFileName: jest.fn((_item, field) => field === undefined ? ['Name'] : field === 'Children' ? ['_Child', 'Name'] : undefined),
            getName: jest.fn(() => ['Name']),
            getFieldConfig: jest.fn((_item, field, configKey) => field === 'Children' && configKey === 'expandArray')
        };
        const expander = new DatapackExpander(definitions as any, createLogger() as any);

        const result = expander.expandDatapack({
            VlocityDataPackType: 'SObject',
            VlocityRecordSObjectType: 'Parent__c',
            VlocityRecordSourceKey: 'Parent__c/Parent',
            Name: 'Parent',
            Children: [
                {
                    Name: 'First',
                    Parent: {
                        VlocityDataPackType: 'VlocityLookupMatchingKeyObject',
                        VlocityLookupRecordSourceKey: 'Other__c/Other'
                    }
                }
            ]
        });

        const outputFile = jest.fn(async () => undefined);
        const remove = jest.fn(async () => undefined);
        await result.writeToFilesystem('/tmp/out', { fs: { outputFile, remove }, prune: true });

        const targetFolder = path.join('/tmp/out', 'Parent_c', 'Parent');
        expect(remove).toHaveBeenCalledWith(targetFolder);
        expect(outputFile).toHaveBeenCalledWith(path.join(targetFolder, 'Parent_Child_First.json'), expect.any(Buffer));
        expect(outputFile).toHaveBeenCalledWith(path.join(targetFolder, 'Parent_DataPack.json'), expect.any(Buffer));
        expect(outputFile).not.toHaveBeenCalledWith(path.join(targetFolder, 'Parent_ParentKeys.json'), expect.anything());
    });
});
