import 'jest';

import { DatapackExporter } from '../export/datapackExporter';
import { DatapackExpander } from '../export/datapackExpander';

describe('DatapackExporter', () => {

    function createLogger() {
        const logger = {
            debug: jest.fn(),
            error: jest.fn(),
            info: jest.fn(),
            verbose: jest.fn(),
            warn: jest.fn(),
            distinct: jest.fn()
        };
        logger.distinct.mockReturnValue(logger);
        return logger;
    }

    function createExporter(options?: {
        matchingKeyFields?: string[];
        describe?: object;
    }) {
        const definitions = {
            getMatchingKeyFields: jest.fn(() => options?.matchingKeyFields ?? []),
            isAutoGeneratedMatchingKey: jest.fn(() => false)
        };
        const salesforce = {
            data: {
                cache: {
                    configure: jest.fn()
                }
            },
            schema: {
                describeSObjectById: jest.fn(async () => options?.describe)
            }
        };
        const matchingKeys = {
            getMatchingKeyDefinition: jest.fn(async (type: string) => ({
                sobjectType: type,
                fields: [],
                returnField: 'Id'
            }))
        };

        const expander = {
            expandDatapack: jest.fn()
        };

        return {
            exporter: new DatapackExporter(
                definitions as any,
                expander as any,
                salesforce as any,
                matchingKeys as any,
                createLogger() as any
            ) as any,
            expander,
            definitions,
            salesforce,
            matchingKeys
        };
    }

    it('keeps primitive filter values when evaluating embedded object filters', () => {
        const { exporter } = createExporter();
        const datapack = {
            id: '001000000000001AAA',
            objectType: 'Account',
            normalizedObjectType: 'Account',
            data: {
                Id: '001000000000001AAA'
            }
        };

        const filter = exporter.buildLookupFilter({
            ParentId: '{Account:Id}',
            IsActive: false,
            Count__c: 0,
            Optional__c: null
        }, datapack);

        expect(filter).toStrictEqual({
            ParentId: '001000000000001AAA',
            IsActive: false,
            Count__c: 0,
            Optional__c: null
        });
    });

    it('awaits lookup references included in matching key objects', async () => {
        const describe = {
            name: 'Child__c',
            fields: [
                { name: 'Parent__c', referenceTo: ['Parent__c'] },
                { name: 'Name', referenceTo: [] }
            ]
        };
        const { exporter } = createExporter({
            matchingKeyFields: ['Parent__c', 'Name'],
            describe
        });
        const parentLookup = {
            VlocityDataPackType: 'VlocityLookupMatchingKeyObject',
            VlocityRecordSObjectType: 'Parent__c',
            VlocityLookupRecordSourceKey: 'Parent__c/Parent'
        };
        exporter.buildLookup = jest.fn(async () => parentLookup);

        const result = await exporter.buildMatchingKeyObject(
            { scope: undefined },
            'VlocityLookupMatchingKeyObject',
            {
                id: 'a01000000000001AAA',
                Id: 'a01000000000001AAA',
                Parent__c: 'a00000000000001AAA',
                Name: 'Child'
            }
        );

        expect(exporter.buildLookup).toHaveBeenCalledWith({ scope: undefined }, 'a00000000000001AAA');
        expect(result.Parent__c).toBe(parentLookup);
        expect(result.Parent__c).not.toHaveProperty('then');
    });

    it('passes export scope to the expander', async () => {
        const { exporter, expander } = createExporter();
        const datapack = {
            VlocityRecordSObjectType: 'OmniProcess',
            VlocityRecordSourceKey: 'OmniProcess/Test'
        };
        exporter.exportObject = jest.fn(async () => ({
            datapack,
            objectType: 'OmniProcess',
            parentKeys: [],
            sourceKey: 'OmniProcess/Test'
        }));

        await exporter.exportObjectAndExpand('0jN000000000001AAA', { scope: 'OmniScript' });

        expect(expander.expandDatapack).toHaveBeenCalledWith(datapack, { scope: 'OmniScript' });
    });

    it('builds embedded objects from the records returned by the embedded lookup even at root-only depth', async () => {
        const childId = 'a01000000000001AAA';
        const parentDatapack = {
            id: 'a00000000000001AAA',
            objectType: 'Parent__c',
            normalizedObjectType: 'Parent__c',
            schema: {
                name: 'Parent__c',
                fields: [],
                childRelationships: []
            },
            data: {
                Id: 'a00000000000001AAA',
                VlocityRecordSourceKey: 'Parent__c/Parent'
            },
            children: {},
            references: {},
            foreignKeys: {},
            sourceKeys: {
                'Parent__c/Parent': 'a00000000000001AAA'
            }
        };
        const childDescribe = {
            name: 'Child__c',
            fields: [
                { name: 'Id', referenceTo: [] },
                { name: 'Name', referenceTo: [] }
            ],
            childRelationships: []
        };
        const definitions = {
            getEmbeddedObjects: jest.fn(item => item.objectType === 'Parent__c'
                ? [{
                    name: 'Child__c',
                    objectType: 'Child__c',
                    filter: { Parent__c: '{Parent__c:Id}' }
                }]
                : []),
            getMatchingKeyFields: jest.fn(() => ['Name']),
            getFieldsWith: jest.fn(() => []),
            isAutoGeneratedMatchingKey: jest.fn(() => false),
            isEmbeddedObject: jest.fn(() => false),
            isFieldIgnored: jest.fn(() => false)
        };
        const salesforce = {
            data: {
                cache: {
                    configure: jest.fn()
                },
                lookup: jest.fn(async () => [{
                    Id: childId,
                    id: childId,
                    Name: 'Child'
                }]),
                lookupById: jest.fn()
            },
            schema: {
                describeSObjectById: jest.fn(async () => childDescribe)
            },
            replaceNamespace: jest.fn((value: string) => value)
        };
        const matchingKeys = {
            getMatchingKeyDefinition: jest.fn(async (type: string) => ({
                sobjectType: type,
                fields: [],
                returnField: 'Id'
            }))
        };

        const exporter = new DatapackExporter(
            definitions as any,
            { expandDatapack: jest.fn() } as any,
            salesforce as any,
            matchingKeys as any,
            createLogger() as any
        ) as any;
        exporter.maxExportDepth = 1;

        await exporter.exportEmbeddedObjects(parentDatapack);

        expect(salesforce.data.lookup).toHaveBeenCalledTimes(1);
        expect(salesforce.data.lookupById).not.toHaveBeenCalledWith(childId);
        expect((parentDatapack.data as any).Child__c).toHaveLength(1);
        expect((parentDatapack.data as any).Child__c[0].VlocityDataPackType).toBe('SObject');
        expect((parentDatapack.data as any).Child__c[0].Name).toBe('Child');
    });
});

describe('DatapackExpander', () => {

    function createLogger() {
        return {
            debug: jest.fn(),
            error: jest.fn(),
            info: jest.fn(),
            verbose: jest.fn(),
            warn: jest.fn()
        };
    }

    it('expands configured array fields into separate files', () => {
        const definitions = {
            getFileName: jest.fn((_item, field) => field === undefined ? ['Name'] : field === 'Children' ? ['_Child', 'Name'] : undefined),
            getName: jest.fn(() => ['Name']),
            getFieldConfig: jest.fn((_item, field, configKey) => field === 'Children' && configKey === 'expandArray')
        };
        const expander = new DatapackExpander(definitions as any, createLogger() as any);

        const result = expander.expandDatapack({
            VlocityDataPackType: 'SObject',
            VlocityRecordSObjectType: 'Parent__c',
            VlocityRecordSourceKey: 'Parent__c/Parent',
            Name: 'Parent',
            Children: [
                { Name: 'First' },
                { Name: 'Second' }
            ]
        });

        expect(Object.keys(result.files).sort()).toStrictEqual([
            'Parent_Child_First.json',
            'Parent_Child_Second.json',
            'Parent_DataPack.json'
        ]);
        expect(JSON.parse(result.files['Parent_DataPack.json'].toString()).Children).toStrictEqual([
            'Parent_Child_First.json',
            'Parent_Child_Second.json'
        ]);
    });

    it('keeps configured null fields inline instead of expanding them into files', () => {
        const definitions = {
            getFileName: jest.fn((_item, field) => field === undefined ? ['Name'] : field === 'PropertySet' ? ['_PropertySet'] : undefined),
            getName: jest.fn(() => ['Name']),
            getFieldConfig: jest.fn()
        };
        const expander = new DatapackExpander(definitions as any, createLogger() as any);

        const result = expander.expandDatapack({
            VlocityDataPackType: 'SObject',
            VlocityRecordSObjectType: 'Parent__c',
            VlocityRecordSourceKey: 'Parent__c/Parent',
            Name: 'Parent',
            PropertySet: null
        });

        expect(Object.keys(result.files).sort()).toStrictEqual([
            'Parent_DataPack.json'
        ]);
        expect(JSON.parse(result.files['Parent_DataPack.json'].toString()).PropertySet).toBeNull();
    });
});
