import 'jest';

import { DatapackExportDefinitionStore } from '../export/exportDefinitionStore';

describe('DatapackExportDefinitionStore', () => {

    describe('definition identity', () => {
        it('keeps definitions for different SObject runtimes under the same Datapack type and scope', () => {
            const store = new DatapackExportDefinitionStore();
            store.load({
                IntegrationProcedure: {
                    objectType: 'OmniProcess',
                    name: [ 'Type', 'SubType' ]
                }
            }, { scope: 'runtime' });
            store.load({
                IntegrationProcedure: {
                    objectType: '%vlocity_namespace%__OmniScript__c',
                    name: [ '%vlocity_namespace%__Type__c', '%vlocity_namespace%__SubType__c' ]
                }
            }, { scope: 'runtime' });

            expect(store.getName({
                datapackType: 'IntegrationProcedure',
                objectType: 'OmniProcess',
                scope: 'runtime'
            })).toEqual([ 'Type', 'SubType' ]);
            expect(store.getName({
                datapackType: 'IntegrationProcedure',
                objectType: 'vlocity_cmt__OmniScript__c',
                scope: 'runtime'
            })).toEqual([ '%vlocity_namespace%__Type__c', '%vlocity_namespace%__SubType__c' ]);
            expect(store.getAvailableScopes({
                datapackType: 'IntegrationProcedure',
                objectType: 'OmniProcess'
            })).toEqual([ 'runtime' ]);
            expect(store.getAvailableScopes({
                datapackType: 'IntegrationProcedure',
                objectType: 'Unrelated__c'
            })).toEqual([]);
            expect(store.getDatapackTypes({ objectType: 'OmniProcess', scope: 'runtime' })).toEqual([
                { datapackType: 'IntegrationProcedure', scope: 'runtime' }
            ]);
            expect(store.getDatapackTypes({ objectType: 'vlocity_cmt__OmniScript__c', scope: 'runtime' })).toEqual([
                { datapackType: 'IntegrationProcedure', scope: 'runtime' }
            ]);
            expect(store.objectDefinitions()).toHaveLength(2);
        });
    });

    describe('#getMatchingKeyFields', () => {
        it('should accept a scalar matchingKeyFields value as a single field', () => {
            const store = new DatapackExportDefinitionStore();
            store.load({
                ConfigurationRule: { objectType: 'SBQQ__ConfigurationRule__c', name: '{Name}', matchingKeyFields: 'Name' as any }
            });

            expect(store.getMatchingKeyFields('SBQQ__ConfigurationRule__c')).toEqual([ 'Name' ]);
        });

        it('should skip definitions without an objectType such as the catch-all SObject definition', () => {
            const store = new DatapackExportDefinitionStore();
            store.load({
                SObject: { ignoreFields: [ 'CurrencyIsoCode' ] } as any,
                ConfigurationRule: { objectType: 'SBQQ__ConfigurationRule__c', name: '{Name}', matchingKeyFields: [ 'Name' ] }
            });

            expect(store.getMatchingKeyFields('SBQQ__ConfigurationRule__c')).toEqual([ 'Name' ]);
            expect(store.getMatchingKeyFields('AttributePicklistValue')).toBeUndefined();
        });

        it('should return an empty array for objects marked with an auto-generated matching key', () => {
            const store = new DatapackExportDefinitionStore();
            store.load({
                PicklistValue: { objectType: 'AttributePicklistValue', name: '{Name}', autoGeneratedMatchingKey: true }
            });

            expect(store.getMatchingKeyFields('AttributePicklistValue')).toEqual([]);
        });

        it('should use the explicitly selected datapack definition when multiple types share an object', () => {
            const store = new DatapackExportDefinitionStore();
            store.load({
                OmniScript: {
                    objectType: 'OmniProcess',
                    name: [ 'Type', 'SubType', 'Language' ],
                    matchingKeyFields: [ 'Type', 'SubType', 'Language' ]
                },
                IntegrationProcedure: {
                    objectType: 'OmniProcess',
                    name: [ 'Type', 'SubType' ],
                    matchingKeyFields: [ 'Type', 'SubType' ]
                }
            }, { scope: 'std' });

            expect(store.getMatchingKeyFields({
                objectType: 'OmniProcess',
                datapackType: 'IntegrationProcedure',
                scope: 'std'
            })).toEqual([ 'Type', 'SubType' ]);
            expect(store.getMatchingKeyFields({
                objectType: 'OmniProcess',
                datapackType: 'OmniScript',
                scope: 'std'
            })).toEqual([ 'Type', 'SubType', 'Language' ]);
        });

        it('should prefer the selected scope when custom definitions use different matching keys', () => {
            const store = new DatapackExportDefinitionStore();
            store.load({
                CustomType: { objectType: 'Shared__c', matchingKeyFields: [ 'StandardKey__c' ] }
            }, { scope: 'standard.yaml' });
            store.load({
                CustomType: { objectType: 'Shared__c', matchingKeyFields: [ 'CustomKey__c' ] }
            }, { scope: 'custom.yaml' });

            expect(store.getMatchingKeyFields({
                objectType: 'Shared__c',
                datapackType: 'CustomType',
                scope: 'custom.yaml'
            })).toEqual([ 'CustomKey__c' ]);
        });
    });

    describe('#isFieldIgnored', () => {

        function createStore() {
            const store = new DatapackExportDefinitionStore();
            store.load({
                Product2: {
                    objectType: 'Product2',
                    matchingKeyFields: [ 'GlobalKey__c' ],
                    ignoreFields: [
                        '%vlocity_namespace%__DRBundleName__c',
                        'IsActive__c',
                        'ContentModifiedById'
                    ]
                }
            });
            return store;
        }

        it('should match a namespace-resolved field against a placeholder ignore entry', () => {
            const store = createStore();
            expect(store.isFieldIgnored({ objectType: 'Product2' }, 'vlocity_cmt__DRBundleName__c')).toBe(true);
        });

        it('should match regardless of namespace casing differences', () => {
            const store = createStore();
            expect(store.isFieldIgnored({ objectType: 'Product2' }, 'vlocity_cmt__drbundlename__c')).toBe(true);
        });

        it('should match a namespaced field against a non-prefixed ignore entry', () => {
            const store = createStore();
            expect(store.isFieldIgnored({ objectType: 'Product2' }, 'vlocity_cmt__IsActive__c')).toBe(true);
        });

        it('should match standard fields without a namespace', () => {
            const store = createStore();
            expect(store.isFieldIgnored({ objectType: 'Product2' }, 'ContentModifiedById')).toBe(true);
        });

        it('should not match fields that are not in the ignore list', () => {
            const store = createStore();
            expect(store.isFieldIgnored({ objectType: 'Product2' }, 'vlocity_cmt__GlobalKey__c')).toBe(false);
        });

        it('should return false when no ignoreFields are configured', () => {
            const store = new DatapackExportDefinitionStore();
            store.load({ Product2: { objectType: 'Product2', matchingKeyFields: [] } });
            expect(store.isFieldIgnored({ objectType: 'Product2' }, 'vlocity_cmt__DRBundleName__c')).toBe(false);
        });

        it('should resolve ignoreFields by datapackType when it differs from the objectType', () => {
            const store = new DatapackExportDefinitionStore();
            store.load({
                PriceRule: {
                    objectType: 'SBQQ__PriceRule__c',
                    matchingKeyFields: [ 'Name' ],
                    ignoreFields: [ 'CurrencyIsoCode' ]
                }
            });
            // Definitions are keyed by datapackType (the YAML key), so the caller must supply it;
            // looking up by objectType alone misses the config.
            expect(store.isFieldIgnored({ datapackType: 'PriceRule', objectType: 'SBQQ__PriceRule__c' }, 'CurrencyIsoCode')).toBe(true);
            expect(store.isFieldIgnored({ objectType: 'SBQQ__PriceRule__c' }, 'CurrencyIsoCode')).toBe(false);
        });

        it('should resolve a definition keyed by SObject type even when a different datapackType is supplied', () => {
            const store = new DatapackExportDefinitionStore();
            // A single SObject can back multiple datapack types; a definition keyed by the SObject type
            // must apply regardless of which datapack type the record is exported under.
            store.load({
                SBQQ__ProductFeature__c: {
                    objectType: 'SBQQ__ProductFeature__c',
                    matchingKeyFields: [ 'Name' ],
                    ignoreFields: [ 'CurrencyIsoCode' ]
                }
            });
            expect(store.isFieldIgnored({ datapackType: 'Product2', objectType: 'SBQQ__ProductFeature__c' }, 'CurrencyIsoCode')).toBe(true);
        });

        it('should apply a global SObject default to every record', () => {
            const store = new DatapackExportDefinitionStore();
            store.load({
                SObject: { objectType: 'SObject', ignoreFields: [ 'CurrencyIsoCode' ] },
                PriceRule: { objectType: 'SBQQ__PriceRule__c', matchingKeyFields: [ 'Name' ] }
            });
            // Matches both a configured datapack and an arbitrary embedded objectType with no own definition.
            expect(store.isFieldIgnored({ datapackType: 'PriceRule', objectType: 'SBQQ__PriceRule__c' }, 'CurrencyIsoCode')).toBe(true);
            expect(store.isFieldIgnored({ datapackType: 'SBQQ__PriceAction__c', objectType: 'SBQQ__PriceAction__c' }, 'CurrencyIsoCode')).toBe(true);
        });

        it('should prefer the datapackType definition over the SObject default', () => {
            const store = new DatapackExportDefinitionStore();
            store.load({
                SObject: { objectType: 'SObject', ignoreFields: [ 'CurrencyIsoCode' ] },
                PriceRule: { objectType: 'SBQQ__PriceRule__c', matchingKeyFields: [ 'Name' ], ignoreFields: [ 'Other__c' ] }
            });
            // The more specific datapackType definition wins, so the SObject default is not merged in.
            expect(store.isFieldIgnored({ datapackType: 'PriceRule', objectType: 'SBQQ__PriceRule__c' }, 'Other__c')).toBe(true);
            expect(store.isFieldIgnored({ datapackType: 'PriceRule', objectType: 'SBQQ__PriceRule__c' }, 'CurrencyIsoCode')).toBe(false);
        });
    });
});
