
export interface SalesforceDebugLevel {
    /**
     * The log category level for Apex code. Includes information about Apex code. Can also include
     * log messages generated by data manipulation language (DML) statements, inline SOQL or SOSL
     * queries, the start and completion of triggers, the start and completion of test methods,
     * and so on.
     */
    apexCode: 'None' | 'Error' | 'Warn' | 'Info' | 'Debug' | 'Fine' | 'Finer' | 'Finest';
    /**
     * The log category level for profiling information. Includes cumulative profiling information,
     * such as the limits for your namespace, the number of emails sent, and so on.
     */
    apexProfiling: 'None' | 'Info' | 'Fine' | 'Finest';
    /**
     * The log category level for callouts. Includes the request-response XML that the server is sending
     * and receiving from an external Web service. The request-response XML is useful when debugging
     * issues related to SOAP API calls.
     */
    callout: 'None' | 'Info' | 'Finest';
    /**
     * The log category for database activity. Includes information about database activity,
     * including every DML statement or inline SOQL or SOSL query.
     */
    database: 'None' | 'Info' | 'Finest';
    /**
     * The log category level for validation rules. Includes information about validation rules,
     * such as the name of the rule, or whether the rule evaluated true or false.
     */
    validation: 'Info' | 'None';
    /**
     * The log category level for Visualforce. Includes information about Visualforce events,
     * including serialization and deserialization of the view state or the evaluation of a
     */
    visualforce: 'None' | 'Info' | 'Fine' | 'Finest';
    /**
     * The log category level for workflow rules. Includes information for workflow rules,
     * such as the rule name and the actions taken.
     */
    workflow: 'None' | 'Error' | 'Warn' | 'Info' | 'Fine' | 'Finer';
    /**
     * The log category level for calls to all system methods, such as the System.debug method.
     */
    system: 'None' | 'Info' | 'Debug' | 'Fine';
}

export interface SalesforceDebugLevelRecord extends SalesforceDebugLevel {
    /**
     * Id if the debug level in Salesforce
     */
    id: string;
    /**
     * Developer name of the debug level
     */
    developerName: string;
}