import * as yaml from 'js-yaml';
import { injectable, Logger, FileSystem } from '@vlocode/core';
import { DescribeSObjectResult, Field, SalesforceService } from '@vlocode/salesforce';
import { asArray, cache, deepFreeze, getErrorMessage, isRecord, normalizeSObjectTypeName, stringEqualsIgnoreCase } from '@vlocode/util';
import { DatapackExportDefinitionStore } from './export/exportDefinitionStore';

/**
 * Matching key definition for an SObject type describing which fields uniquely identify a record.
 */
export interface VlocityMatchingKey {
    /**
     * SObject type to which the matching key applies.
     */
    readonly sobjectType: string;
    /**
     * Fields that together uniquely identify a record of this SObject type. An empty array means the
     * object is explicitly key-less: records are always inserted and exports use generated source keys.
     */
    readonly fields: ReadonlyArray<string>;
    /**
     * Field returned when looking up records by matching key; defaults to `Id`.
     */
    readonly returnField: string;
}

interface DRMatchingKeyRecord {
    id: string;
    objectAPIName: string;
    matchingKeyFields: string;
    returnKeyField: string;
}

/**
 * Central service that manages matching key fields for SObject types. Matching keys determine which
 * fields uniquely identify a record and are used for looking up existing records during deployment
 * (upsert fields), for generating datapack source keys during export and for building export queries.
 *
 * Matching keys are object-scoped: one SObject type resolves to exactly one set of matching key fields
 * regardless of the datapack type or export scope in which it is used. This guarantees that a record
 * exported or referenced from different datapacks always resolves to the same identity.
 *
 * Matching keys are loaded from the following sources; the first source that defines a key for an
 * object wins:
 * 1. Matching key files (JSON or YAML, `matching-keys.json`/`.yaml` by default, see {@link setMatchingKeyFiles})
 * 2. Export definitions (`matchingKeyFields` or `autoGeneratedMatchingKey` in the definition yaml)
 * 3. The org's `DRMatchingKey__mdt` records
 * 4. Built-in defaults for standard objects that need a specific key configuration
 *
 * When no source defines a key the service falls back to a required unique field, the `DeveloperName`
 * field or the object's name field. Objects that link to a parent through a master-detail relationship
 * always include the relationship field(s) in their matching key so child records are matched within
 * their parent. When no matching key can be determined at all the object is treated as key-less:
 * records are always inserted on deployment and exported with generated source keys. Top-level
 * datapacks require a matching key which is enforced by the deployment and export flows.
 */
@injectable.singleton()
export class MatchingKeyService {

    /**
     * Default matching key files loaded from the working directory when present.
     */
    public static readonly defaultMatchingKeyFiles = [ 'matching-keys.json', 'matching-keys.yaml', 'matching-keys.yml' ];

    /**
     * Extra matching key files registered through {@link setMatchingKeyFiles}.
     */
    private extraMatchingKeyFiles: string[] = [];

    /**
     * Resolved matching keys by normalized SObject type name.
     */
    private readonly resolvedKeys = new Map<string, Promise<VlocityMatchingKey>>();

    /**
     * Matching keys loaded from {@link matchingKeyFiles}; reset when new files are registered.
     */
    private fileMatchingKeys?: Promise<Map<string, string[]>>;

    /**
     * Built-in matching key defaults for objects that require a specific key configuration,
     * keyed by normalized (lower case, namespace-less) SObject type. An empty array marks the
     * object as key-less causing records to always be inserted.
     */
    private readonly defaultMatchingKeys: Record<string, string[]> = {
        // OmniDataTransformItem mappings are purged and re-inserted on deployment
        omnidatatransformitem: [],
        omnidatatransform: [ 'VersionNumber', 'Name' ],
        omniuicard: [ 'VersionNumber', 'Name' ],
        customobjectmap__c: [
            '%vlocity_namespace%__DestinationParentObject__c',
            '%vlocity_namespace%__SourceParentObject__c',
        ],
        customfieldmap__c: [
            '%vlocity_namespace%__DestinationFieldName__c',
            '%vlocity_namespace%__DestinationSObjectType__c',
            '%vlocity_namespace%__SourceFieldName__c',
            '%vlocity_namespace%__SourceSObjectType__c',
        ],
        calculationmatrixversion: [ 'VersionNumber', 'CalculationMatrixId' ],
        calculationprocedureversion: [ 'VersionNumber', 'CalculationProcedureId' ],
        calculationmatrixcolumn: [ 'CalculationMatrixId', 'Name' ],
        recordtype: [ 'SobjectType', 'DeveloperName' ],
        user: [ 'Username' ],
        group: [ 'DeveloperName' ],
        // GroupMember records have no identifying fields and are always inserted
        groupmember: [],
    };

    constructor(
        private readonly logger: Logger,
        private readonly salesforce: SalesforceService,
        private readonly exportDefinitions: DatapackExportDefinitionStore,
        private readonly fs: FileSystem) {
    }

    @cache({ unwrapPromise: true, cacheExceptions: true })
    private get orgMatchingKeys() {
        return this.loadOrgMatchingKeys();
    }

    /**
     * Pre-loads the matching keys from the org and the registered matching key files so subsequent
     * matching key resolutions do not require additional callouts. Idempotent; safe to call multiple times.
     */
    public async initialize(): Promise<this> {
        await Promise.all([ this.orgMatchingKeys, this.getFileMatchingKeys() ]);
        return this;
    }

    /**
     * Set the matching key files to load in addition to the default `matching-keys` file in the
     * working directory. Files are JSON or YAML objects mapping an SObject type to an array of
     * matching key field names:
     * ```yaml
     * Product2: [ ProductCode ]
     * "%vlocity_namespace%__PriceList__c": [ Name ]
     * ```
     * Matching keys from files take precedence over keys defined in export definitions and in the org;
     * entries in later files override earlier files. Replaces previously set files and resets already
     * resolved matching keys so new resolutions reflect the specified files.
     * @param files Paths of the matching key files to load
     */
    public setMatchingKeyFiles(...files: string[]): this {
        this.extraMatchingKeyFiles = [ ...files ];
        this.fileMatchingKeys = undefined;
        this.resolvedKeys.clear();
        return this;
    }

    /**
     * Get the matching key for the specified SObject type. Resolution is cached per object type and
     * the same key is returned for the import, export and deployment flows.
     *
     * Fields configured through one of the matching key sources are validated against the object
     * describe and returned using their API name; configuring a field that does not exist on the
     * object is an error. Master-detail relationship fields of the object are always part of the
     * returned matching key.
     *
     * @param sobjectType SObject type with or without (placeholder) namespace prefix
     * @returns The matching key for the object; `fields` is empty for key-less objects, either
     * explicitly configured as such or because no matching key could be determined.
     * @throws When the object does not exist in the target org or a configured field does not exist on the object.
     */
    public async getMatchingKey(sobjectType: string): Promise<VlocityMatchingKey> {
        if (!sobjectType) {
            throw new Error('Cannot resolve the matching key for an undefined or empty SObject type');
        }
        const typeKey = normalizeSObjectTypeName(sobjectType);
        let matchingKey = this.resolvedKeys.get(typeKey);
        if (!matchingKey) {
            // Freeze the resolved key so the same instance can be shared with all callers
            this.resolvedKeys.set(typeKey, matchingKey = this.resolveMatchingKey(sobjectType)
                .then(key => deepFreeze({ ...key, fields: [ ...key.fields ] })));
        }
        return matchingKey;
    }

    private async resolveMatchingKey(sobjectType: string): Promise<VlocityMatchingKey> {
        const typeKey = normalizeSObjectTypeName(sobjectType);
        const configuredFields = await this.getConfiguredFields(sobjectType);
        const returnField = (await this.orgMatchingKeys).get(typeKey)?.returnField ?? 'Id';

        if (configuredFields?.length === 0) {
            // Explicitly key-less object; always insert on deployment and use generated keys on export.
            // Master-detail fields are deliberately not added as they would (partially) match sibling records.
            return { sobjectType, fields: [], returnField };
        }

        const describe = await this.salesforce.schema.describeSObject(sobjectType, false);
        if (!describe) {
            if (configuredFields) {
                // Without a describe the configured fields cannot be validated; return them as-is
                return { sobjectType, fields: configuredFields, returnField };
            }
            throw new Error(`Unable to determine matching key fields for ${sobjectType}: no such object in the target org`);
        }

        const fields = configuredFields
            ? await this.validateFields(describe, configuredFields)
            : this.getFallbackFields(describe);

        // Records of objects with a master-detail relation are always matched within their parent(s).
        // A single parent field without any other key field does not form a key by itself as it would
        // match all sibling records under the same parent; a combination of multiple parent fields
        // identifies a junction record (e.g. PricebookEntry) and is used as key
        const parentFields = this.getMasterDetailFields(describe);
        if (fields.length || parentFields.length > 1) {
            for (const parentField of parentFields) {
                if (!stringEqualsIgnoreCase(parentField, fields)) {
                    fields.push(parentField);
                }
            }
        }

        if (!fields.length) {
            this.logger.warn(
                `No matching key fields could be determined for ${describe.name}; ` +
                `records are always inserted on deployment and exported with generated source keys -- ` +
                `configure matching key fields in a matching key file or export definition to enable record matching`
            );
        } else {
            this.logger.verbose(`Matching key for ${describe.name}: [${fields.join(', ')}]`);
        }
        return { sobjectType: describe.name, fields, returnField };
    }

    /**
     * Get the matching key fields configured for an object checking each source in order of
     * precedence: matching key files, export definitions, org matching keys and built-in defaults.
     * @returns The configured fields or `undefined` when no source defines a key for the object
     */
    private async getConfiguredFields(sobjectType: string): Promise<ReadonlyArray<string> | undefined> {
        const typeKey = normalizeSObjectTypeName(sobjectType);

        const fileFields = (await this.getFileMatchingKeys()).get(typeKey);
        if (fileFields) {
            return fileFields;
        }

        const definitionFields = this.exportDefinitions.getMatchingKeyFields(sobjectType);
        if (definitionFields) {
            return definitionFields;
        }

        const orgKey = (await this.orgMatchingKeys).get(typeKey);
        if (orgKey?.fields.length) {
            // Org matching keys are validated lazily per resolved type so that loading them
            // does not require describing every object with a matching key in the org
            const orgFields = await this.validateOrgMatchingKeyFields(orgKey.sobjectType, orgKey.fields);
            if (orgFields.length) {
                return orgFields;
            }
        }

        return this.defaultMatchingKeys[typeKey];
    }

    /**
     * Validate that each of the configured matching key fields exists on the object and
     * resolve them to their proper API names.
     * @throws When one of the fields does not exist on the object
     */
    private async validateFields(describe: DescribeSObjectResult, fields: ReadonlyArray<string>): Promise<string[]> {
        const resolvedFields = new Array<string>();
        for (const field of fields) {
            const fieldDescribe = await this.salesforce.schema.describeSObjectField(describe.name, field, false);
            if (!fieldDescribe) {
                throw new Error(`Matching key field '${field}' does not exist on ${describe.name}`);
            }
            resolvedFields.push(fieldDescribe.name);
        }
        return resolvedFields;
    }

    /**
     * Determine the matching key fields for an object without matching key configuration:
     * a required unique field, the `DeveloperName` field or the object's name field.
     */
    private getFallbackFields(describe: DescribeSObjectResult): string[] {
        const uniqueField = describe.fields.find(field => field.unique && !field.nillable && !field.autoNumber && !field.calculated);
        if (uniqueField) {
            return [ uniqueField.name ];
        }

        // DeveloperName is stable across orgs which makes it a better key than the name field
        const developerName = describe.fields.find(field => field.name === 'DeveloperName');
        if (developerName) {
            return [ developerName.name ];
        }

        const nameField = describe.fields.find(field => field.nameField && !field.autoNumber && !field.calculated);
        if (nameField) {
            return [ nameField.name ];
        }

        return [];
    }

    /**
     * Get the master-detail relationship fields of an object. Custom master-detail fields report a
     * `relationshipOrder`; standard master-detail-like relationships are required cascade-delete lookups.
     */
    private getMasterDetailFields(describe: DescribeSObjectResult): string[] {
        return describe.fields
            .filter(field => field.type === 'reference' && this.isMasterDetailField(field))
            .map(field => field.name);
    }

    private isMasterDetailField(field: Field): boolean {
        return typeof field.relationshipOrder === 'number' || (field.cascadeDelete === true && field.nillable === false);
    }

    private getFileMatchingKeys(): Promise<Map<string, string[]>> {
        return this.fileMatchingKeys ??= this.loadMatchingKeyFiles();
    }

    private async loadMatchingKeyFiles(): Promise<Map<string, string[]>> {
        const matchingKeys = new Map<string, string[]>();
        for (const file of [ ...MatchingKeyService.defaultMatchingKeyFiles, ...this.extraMatchingKeyFiles ]) {
            if (!await this.fs.pathExists(file)) {
                if (!MatchingKeyService.defaultMatchingKeyFiles.includes(file)) {
                    // Only the default matching key files are optional
                    this.logger.warn(`Matching key file does not exist: ${file}`);
                }
                continue;
            }

            try {
                const entries = yaml.load(await this.fs.readFileAsString(file));
                if (!isRecord(entries)) {
                    throw new Error('file should contain an object mapping SObject types to matching key field arrays');
                }
                for (const [ sobjectType, fields ] of Object.entries(entries)) {
                    matchingKeys.set(normalizeSObjectTypeName(sobjectType), asArray(fields ?? []).map(String));
                    this.logger.verbose(`Matching key fields for ${sobjectType} set from ${file}`);
                }
            } catch (error) {
                this.logger.warn(`Failed to load matching key file ${file}: %s`, error);
            }
        }
        return matchingKeys;
    }

    private async loadOrgMatchingKeys(): Promise<Map<string, VlocityMatchingKey>> {
        const matchingKeys = new Map<string, VlocityMatchingKey>();
        for (const matchingKey of await this.queryOrgMatchingKeys()) {
            matchingKeys.set(normalizeSObjectTypeName(matchingKey.sobjectType), matchingKey);
        }
        return matchingKeys;
    }

    private async queryOrgMatchingKeys(): Promise<Array<VlocityMatchingKey>> {
        this.logger.verbose('Querying matching keys from Salesforce');

        let matchingKeyResults: DRMatchingKeyRecord[];
        try {
            matchingKeyResults = await this.salesforce.data.lookup('%vlocity_namespace%__DRMatchingKey__mdt', undefined, 'all');
        } catch (error) {
            this.logger.warn(`Unable to load matching keys from Salesforce; using configured and inferred matching keys only: ${getErrorMessage(error)}`);
            return [];
        }

        // Fields are validated lazily when a matching key is resolved (see getConfiguredFields)
        const matchingKeyObjects = matchingKeyResults
            // Ignore incomplete matching key records; a malformed record in the org should not break matching key resolution
            .filter(record => record.objectAPIName && record.matchingKeyFields)
            .map(record => ({
                sobjectType: record.objectAPIName,
                fields: record.matchingKeyFields.split(',').map(field => field.trim()).reverse(),
                returnField: record.returnKeyField
            }));

        this.logger.log(`Loaded ${matchingKeyObjects.length} matching key definitions from Salesforce`);
        return matchingKeyObjects;
    }

    /**
     * Validate the fields of a matching key loaded from the org dropping fields that do not exist or
     * are not accessible. Unlike configured matching keys org matching keys are not treated as an
     * error when invalid as they are managed in the org and may reference fields the current user
     * cannot access.
     */
    private async validateOrgMatchingKeyFields(sobjectType: string, fields: ReadonlyArray<string>): Promise<string[]> {
        const resolvedFields = new Array<string>();

        for (const field of fields) {
            const fieldDescribe = await this.salesforce.schema.describeSObjectField(sobjectType, field, false);
            if (fieldDescribe) {
                resolvedFields.push(fieldDescribe.name);
            } else {
                if (!await this.salesforce.schema.isSObjectFieldDefined(sobjectType, field)) {
                    this.logger.warn(`${sobjectType}: matching key field '${field}' is not accessible -- update the profile of the current user to fix this warning`);
                } else {
                    this.logger.error(`${sobjectType}: matching key field '${field}' does not exist -- remove this field from the matching key definitions in Salesforce to fix this error`);
                }
            }
        }

        return resolvedFields;
    }

}
