name: Update Documentation

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: ['Release']
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup workspace
        uses: ./.github/actions/setup-workspace
        with:
          node-version: '20'
          install-os-deps: 'false'

      - name: Generate Documentation
        run: pnpm run docs

      - name: Fix permissions
        run: |
          chmod -c -R +rX "docs/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
